
import { Geist} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import InterectionsProvider, { InterectionsContext } from "@/context/installcontext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light" 
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <NavBar />
        <InterectionsProvider>
        {children}
        </InterectionsProvider>
        <Footer />
        <ToastContainer />
        </body>
    </html>
  );
}
